travis:
  secure:
    BINSTAR_TOKEN: CsUotVPBfuxZZJ2dtfdr79XuPim193Zi2xn7VdPWDabHhen2MIV4pljSoILTsphW2Bzxja/kqaPYTIh0K11btUJX6HAfVJSvfaA3aves0mnoT3yJB8ONH8ciV94Xw6tSed85dnUfA1LAv94pvRA7r1le07+fXZZpUEWY8VP7kThqMJtmnBJ1+CzrvJ/ihdro485JhTga70s99srgAG7VPGSambRXZj7N4HvpdgheYkhF3gHEorACOH/OjtyooxFcHx1ERyxSz948oYuBsnRD1OX80f2a4vY9guCvTZQQzJfPzM7yw26JAGcuvCBErL8jEf1WVyTb7YL6R6XpYMO911nZbzz9BI427ABMJ2AbK98wQPqemCmSf54hq0yLu/usmuAwnx3oQqHmWxFkjAk1f1eghdjymNUeoC2xIAz/xILjPS+/xvHC3vf8WkWBfkPViENqMgjalWk0apSRy9IqvpP0snYAnF4SLH+YgEV5U5OVUcuFBZ2vQ5ruyQG8N2bFr8EpM8VvfvMirVOd22omhwS2mp8S6pKQGgcIYluC1XcS+OURtlFeiTVTP2Im32gRH+Iwo3Tu5vIscWD+0BwW6f+kbmE4SDFRJYLlGOR7Y1Om2o2PPl9qcHgSNJofjq8aY8/O++y5zWhEPmPCOJlzmkTMXPIsp5C8ovxohxjRwqI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
